package by.pvt.dto;

import java.util.Date;

public class Clients {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clients.clients_id
     *
     * @mbg.generated Tue Jul 23 22:18:11 MSK 2019
     */
    private Integer clientsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clients.first_name
     *
     * @mbg.generated Tue Jul 23 22:18:11 MSK 2019
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clients.date_of_birth
     *
     * @mbg.generated Tue Jul 23 22:18:11 MSK 2019
     */
    private Date dateOfBirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clients.male_female
     *
     * @mbg.generated Tue Jul 23 22:18:11 MSK 2019
     */
    private String maleFemale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clients.email
     *
     * @mbg.generated Tue Jul 23 22:18:11 MSK 2019
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clients.clients_id
     *
     * @return the value of clients.clients_id
     *
     * @mbg.generated Tue Jul 23 22:18:11 MSK 2019
     */
    public Integer getClientsId() {
        return clientsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clients.clients_id
     *
     * @param clientsId the value for clients.clients_id
     *
     * @mbg.generated Tue Jul 23 22:18:11 MSK 2019
     */
    public void setClientsId(Integer clientsId) {
        this.clientsId = clientsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clients.first_name
     *
     * @return the value of clients.first_name
     *
     * @mbg.generated Tue Jul 23 22:18:11 MSK 2019
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clients.first_name
     *
     * @param firstName the value for clients.first_name
     *
     * @mbg.generated Tue Jul 23 22:18:11 MSK 2019
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clients.date_of_birth
     *
     * @return the value of clients.date_of_birth
     *
     * @mbg.generated Tue Jul 23 22:18:11 MSK 2019
     */
    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clients.date_of_birth
     *
     * @param dateOfBirth the value for clients.date_of_birth
     *
     * @mbg.generated Tue Jul 23 22:18:11 MSK 2019
     */
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clients.male_female
     *
     * @return the value of clients.male_female
     *
     * @mbg.generated Tue Jul 23 22:18:11 MSK 2019
     */
    public String getMaleFemale() {
        return maleFemale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clients.male_female
     *
     * @param maleFemale the value for clients.male_female
     *
     * @mbg.generated Tue Jul 23 22:18:11 MSK 2019
     */
    public void setMaleFemale(String maleFemale) {
        this.maleFemale = maleFemale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clients.email
     *
     * @return the value of clients.email
     *
     * @mbg.generated Tue Jul 23 22:18:11 MSK 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clients.email
     *
     * @param email the value for clients.email
     *
     * @mbg.generated Tue Jul 23 22:18:11 MSK 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }
}